users/urls.py
# Define URL patterns for users

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'users'

urlpatterns = [
  # Login page
  path('login/',
      auth_views.LoginView.as_view(template_name='users/login.html'),
      name='login'),

  # Logout page
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),

  # Registration page
  path('register/', views.register, name='register'),
]

xlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('',include('xlogs.urls')),
]  

xlogs/urls.py
# Defines URL patterns for xlogs

from django.urls import path

from . import views

app_name = 'xlogs'

urlpatterns = [
	#Home Page
	path('',views.index,name='index'),

    #Show all categories
    path('categories/', views.categories, name='categories'),

    #Details page foe single category
    path('categories/<int:category_id>/', views.category, name='category'),

    #Page for adding a new topic
    path('new_cat/', views.new_cat, name='new_cat'),

    #Page for adding a new entry
    path('new_entry/<int:category_id>/', views.new_entry, name='new_entry'),

    #Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),


] 

users/models.py
from django.db import models

# Create your models here.

xlogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        # returns a string representation of the mode
        return self.text

class Entry(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] +"..."

xlogs/forms.py
from django import forms

from .models import Category, Entry

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['text']
        labesl = {'text':''} 

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = {'text'}
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})} 

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import login,  authenticate
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse


# Create your views here.

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('xlogs:index')) 

def register(request):
    # Register a new user
    if request.method != 'POST':
        # Display blank registration form
        form = UserCreationForm()
    else: 
        # Process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user= form.save()
            # Log user in and redirest them to homepage
            authenticated_user = authenticate(username=new_user.username,
                    password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('xlogs:index'))
    
    context = {'form':form}
    return render(request, 'users/register.html', context)

        

xlogs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Category, Entry
from .forms import CategoryForm, EntryForm

# Create your views here.


def index(request):
    # Home page
    return render(request, 'xlogs/index.html')

@login_required 

def categories(request):
    #show all categories
    categories = Category.objects.filter(owner=request.user).order_by('date_added')
    context = {'categories':categories}
    return render(request,'xlogs/categories.html', context)

@login_required

def category(request, category_id):
    #Show a single category and all entries
    category = Category.objects.get(id=category_id)
    # Make sure the category belongs to current user
    if category.owner != request.user:
        raise Http404
    entries = category.entry_set.order_by('-date_added')
    context = {'category': category, 'entries': entries}
    return render(request, 'xlogs/category.html', context)


@login_required

def new_cat(request):
    if request.method != 'POST':
        #No data submitted; create blank form
        form = CategoryForm()
    else:
        #POST data submitted; process data
        form = CategoryForm(data=request.POST)
        if form.is_valid():
            new_cat = form.save(commit=False)
            new_cat.owner = request.user
            new_cat.save()
            return HttpResponseRedirect(reverse('xlogs:categories'))

    context = {'form':form}
    return render(request, 'xlogs/new_cat.html',context) 

@login_required

def new_entry(request, category_id):
    #Add a new entry for a particular category
    category = Category.objects.get(id=category_id)

    if request.method != 'POST':
        #No data submitted;create blank form
        form = EntryForm()
    else:
        #POST data submitted; process data
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.category = category
            new_entry.save()
            return HttpResponseRedirect(reverse('xlogs:category', args=[category_id])) 

    context = {'category':category, 'form':form} 
    return render(request, 'xlogs/new_entry.html', context) 

@login_required

def edit_entry(request, entry_id):
    #Edit an existing entry
    entry = Entry.objects.get(id=entry_id)
    category = entry.category
    if category.owner != request.user:
        raise Http404

    if request.method != 'POST':
        #Initial request: pre fill form with current entry
        form = EntryForm(instance=entry)
    else:
        #POST data submitted; process data
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('xlogs:category',args=[category.id]))

    context = {'entry':entry, 'category':category, 'form':form}
    return render(request,'xlogs/edit_entry.html', context)

users/templates/users/login.html
{% extends "xlogs/base.html" %}

{% block content %}

  {% if form.errors %}
    <p>Your username and password didnt match. Please try again.</p>
  {% endif %}

  <form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">log in</button>
    
    <input type="hidden" name="next"
      value="{% url 'xlogs:index' %}" />
  </form> 

{% endblock content %}

users/templates/users/register.html
{% extends 'xlogs/base.html' %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

     <button name="submit">register</button>
     <input type="hidden" name="next" value"{% url 'xlogs:index' %}"  />
  </form>

{% endblock content %}


	

xlogs/templates/xlogs/base.html
<p>
  <a href="{% url 'xlogs:index' %}">X LOG</a> - 
  <a href="{% url 'xlogs:categories' %}">Categories</a> -
  {% if user.is_authenticated %}
    Hello, {{ user.username }}.
    <a href="{% url 'users:logout' %}">log out</a>
  {% else %}
    <a href="{% url 'users:register' %}">register</a> -
    <a href="{% url 'users:login' %}">log in</a>
  {% endif %} 
<p>
{% block content %}{% endblock content %} 

xlogs/templates/xlogs/categories.html
{% extends "xlogs/base.html" %}

{% block content %}

  <p>Categories</p>

  <ul>
	  {% for category in categories %}
	    <li>
		  <a href="{% url 'xlogs:category' category.id %}">{{ category }}</a>
		  
	    </li>
	  {% empty %}

	    <li> No categories have been added yet. </li>
 
	  {% endfor %}
  </ul>
  <a href="{% url 'xlogs:new_cat' %}">Add a new category:</a> 

{% endblock content %}

xlogs/templates/xlogs/category.html
{% extends "xlogs/base.html" %}

{% block content %}

  <p>Category:{{ category }}</p>

  <p>Entries:</p>
  <p>
    <a href="{% url 'xlogs:new_entry' category.id %}">add new entry</a>
  <p>

  <ul>
  {% for entry in entries %}
    <li>
      <p>{{entry.date_added|date:'M d, Y H:i'}}</p>
      <p>{{entry.text|linebreaks }}</p>
      <p>
        <a href="{% url 'xlogs:edit_entry' entry.id %}">edit entry</a>
      </p>
    </li> 
  {% empty %}
    <li>
      There are no entries for this category yet.
    </li>

  {% endfor %}
  </ul>

{% endblock content %}

xlogs/templates/xlogs/edit_entry.html
{% extends "xlogs/base.html" %}

{% block content %}
    
  <p><a href="{% url 'xlogs:category' category.id %}">{{ categrory }}</a></p>

  <p>Edit entry:</p>

  <form action="{% url 'xlogs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="sumbmit"> save changes</button>
  </form>

{% endblock content %}

xlogs/templates/xlogs/index.html
{% extends "xlogs/base.html" %}

{% block content %}

  <p> X log helps you record anything that has to do with X. <p>

{% endblock content %} 

xlogs/templates/xlogs/new_cat.html
{% extends "xlogs/base.html" %}

{% block content %}
  <p> Add a new category:</p>

  <form action="{% url 'xlogs:new_cat' %}" method='post'>
	  {% csrf_token %}
	  {{form.as_p}}
	  <button name="submit"> add category</button>
  </form>

{% endblock content %}

xlogs/templates/xlogs/new_entry.html
{% extends "xlogs/base.html" %}

{% block content %}

    <p><a href="{% url 'xlogs:category' category.id %}">{{ category }}</a></p>

    <p> Add a new entry:</p>
    <form action= "{% url 'xlogs:new_entry' category.id %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <button name='submit'>add entry</button>
    </form>

{% endblock content %}